package:
  name: q2-pinocchio
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-feature-classifier {{ qiime2_epoch }}.*
    - samtools
    - minimap2
    - beautifulsoup4
    - nanoplot
    - chopper
    - gzip

  build:
  - setuptools
  - versioningit

test:
  requires:
    - parameterized
  imports:
    - q2_pinocchio
    - qiime2.plugins.pinocchio
  commands:
    - pytest --pyargs q2_pinocchio

about:
  home: https://github.com/bokulich-lab/q2-pinocchio
  license: BSD-3-Clause
  license_family: BSD
